"""One-liners for the user emails, one picked at random per email (``notify.render_user_event``):
``GOLF_QUIPS`` wish the golfer luck on a booked / upgraded tee time; ``MISS_QUIPS`` console them
when the morning run could not get one. Plain ASCII-friendly text, one line each, no names."""

from __future__ import annotations

GOLF_QUIPS: tuple[str, ...] = (
    "Shoot 'em low!",
    "Remember: trees are 90% air. So are screen doors.",
    "Fairways and greens!",
    "May your drives be long and your putts be short.",
    "Keep it in the short grass.",
    "Grip it and rip it.",
    "Never up, never in.",
    "Drive for show, putt for dough.",
    "The water is just a very flat hazard. Aim elsewhere.",
    "Any ball you can find is a good ball.",
    "A bad day on the course still beats a good day at the office.",
    "Swing easy. The ball isn't going anywhere until you hit it.",
    "If you're going to three-putt, three-putt with confidence.",
    "Hit 'em straight, and if you can't, hit 'em far.",
    "The sand is for the beach. Stay out of it.",
    "Count your blessings, not your strokes.",
    "Mulligans are between you and your conscience.",
    "Tee it high and let it fly.",
    "It's not a slice, it's a power fade.",
    "Keep your head down and your spirits up.",
    "May the golf gods smile upon your short game.",
    "Every hole is a fresh start. Even the 18th.",
    "Play the ball as it lies, and lie about the score.",
    "The first tee is the only place you're guaranteed par.",
    "Bring extra balls. Not for you, for the pond.",
    "Aim small, miss small.",
    "Relax. The pin can't move.",
    "Here's to a birdie or two.",
    "May every putt find the bottom of the cup.",
    "Wind at your back and the pin in reach.",
    "Hit it where they ain't: the trees, that is.",
    "Golf is a good walk, so enjoy the walk.",
    "Smooth tempo, soft hands, big smile.",
    "The rough is only rough if you're in it.",
    "Your best round is still out there. Maybe this is it.",
    "Take a club more. You always need a club more.",
    "Putt like nobody's watching.",
    "Great shots are remembered; the rest are practice swings.",
    "Swing like you mean it, putt like you know it.",
    "Leave the pin in if it makes you feel better.",
    "Here's hoping the only hazard is the snack cart line.",
    "Keep calm and chip it close.",
    "May your divots be small and your scorecard smaller.",
    "Somewhere out there is a hole-in-one with your name on it.",
    "When in doubt, blame the wind.",
    "Play fast, laugh often, and replace your divots.",
    "The ball doesn't know you missed the last one.",
    "Sunscreen on, phone off, driver out.",
    "A par is a birdie that got nervous. Stay calm.",
    "Hit 'em long and hit 'em straight. Or just hit 'em.",
    "Go get that birdie.",
    "See you on the first tee.",
)


MISS_QUIPS: tuple[str, ...] = (
    "Even the pros miss a cut now and then.",
    "The course will still be there next week, and so will we.",
    "Call it a rain check from the golf gods.",
    "Some days the tee sheet wins. We'll get the next one.",
    "Think of it as extra time on the practice green.",
    "No tee time, no three-putts. Small mercies.",
    "The driving range never sells out.",
    "You can't win them all, but you can always book the next one.",
    "A missed tee time is just a mulligan on the calendar.",
    "Keep your grips dry and your hopes up.",
    "Every great round starts with a week you didn't play.",
    "Chin up: the 19th hole is open every day.",
)
